server:
  port: 8000

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: root
    password: 1234
  sql:
    init:
      mode: always

jwt:
  secret-key: a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0
  expiration:
#    access-token: 300000 # 5 minutes: 1000 (1초) * 60 * 5 = 300000
    access-token: 86400000 # TODO: remove
    refresh-token: 86400000 # 1 day: 1000 (1초) * 60 * 60 * 24 = 86400000

logging:
  level:
    org:
      hibernate:
        resource:
          transaction: DEBUG
      springframework:
        Security: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        transaction:
          interceptor: TRACE
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG